#ifndef GUARD_CONSTANTS_BOSS_INTRO_H
#define GUARD_CONSTANTS_BOSS_INTRO_H

#define BOSS_INTRO_EDWARDS  0
#define BOSS_INTRO_ALLISON  1
#define BOSS_INTRO_RED_FATALITY 2
#define BOSS_INTRO_THE_ONI  3
#define BOSS_INTRO_YIFFER   4
#define BOSS_INTRO_COUNT    5

#endif // GUARD_CONSTANTS_BOSS_INTRO_H
