#ifndef GUARD_CONSTANTS_BOSS_INTRO_H
#define GUARD_CONSTANTS_BOSS_INTRO_H

#define BOSS_INTRO_EDWARDS  0
#define BOSS_INTRO_ALLISON  1
#define BOSS_INTRO_COUNT    2

#endif // GUARD_CONSTANTS_BOSS_INTRO_H
